---

- hosts: apache2
  remote_user: root
  roles:
    - hswong3i.apache2
    - role: hswong3i.ufw
      ufw:
        - { to_port: "{{ apache2_http_port }}", proto: "tcp", rule: "allow" }
        - { to_port: "{{ apache2_https_port }}", proto: "tcp", rule: "allow" }

