---

- hosts: bamboo
  remote_user: root
  roles:
    - hswong3i.bamboo
    - hswong3i.mysql_connector_java
    - role: hswong3i.ufw
      ufw:
        - { to_port: "{{ bamboo_connector_port }}", proto: "tcp", rule: "allow" }
        - { to_port: "{{ bamboo_server_port }}", proto: "tcp", rule: "allow" }
