---

- hosts: confluence
  remote_user: root
  roles:
    - hswong3i.confluence
    - hswong3i.mysql_connector_java
    - role: hswong3i.ufw
      ufw:
        - { to_port: "{{ confluence_connector_port }}", proto: "tcp", rule: "allow" }
        - { to_port: "{{ confluence_server_port }}", proto: "tcp", rule: "allow" }
