---

- hosts: fisheye
  remote_user: root
  roles:
    - hswong3i.fisheye
    - hswong3i.mysql_connector_java
    - role: hswong3i.ufw
      ufw:
        - { to_port: "{{ fisheye_connector_port }}", proto: "tcp", rule: "allow" }
        - { to_port: "{{ fisheye_server_port }}", proto: "tcp", rule: "allow" }
