---

- hosts: mysql
  remote_user: root
  roles:
    - role: hswong3i.mysql_vhosts
      when: groups['mariadb'] is not defined or inventory_hostname not in groups['mariadb']

- hosts: mariadb
  remote_user: root
  roles:
    - hswong3i.mariadb_vhosts

- hosts: postgresql
  remote_user: root
  roles:
    - hswong3i.postgresql_vhosts

- hosts: fisheye
  remote_user: root
  roles:
    - hswong3i.fisheye
    - hswong3i.mysql_connector_java
    - role: hswong3i.ufw
      ufw:
        - { to_port: "{{ fisheye_connector_port }}", proto: "tcp", rule: "allow" }
        - { to_port: "{{ fisheye_server_port }}", proto: "tcp", rule: "allow" }

- hosts: apache2
  remote_user: root
  roles:
    - hswong3i.apache2_vhosts
