---

- hosts: gluster
  remote_user: root
  tasks:
    - name: stop all volumes
      gluster_volume:
        name: "{{ item.name }}"
        state: "stopped"
        force: "yes"
      with_items: "{{ gluster_volume }}"
      run_once: yes
      ignore_errors: yes

    - name: stop all nodes
      service:
        name: "{{ item }}"
        state: "stopped"
      with_items:
        - "glusterfs-server"
        - "rpcbind"
