---

- hosts: gluster
  remote_user: root
  tasks:
    - name: start all nodes
      service:
        name: "glusterfs-server"
        state: "started"

    - name: start all volumes
      gluster_volume:
        name: "{{ item.name }}"
        state: "started"
        force: "yes"
      with_items: "{{ gluster_volume }}"
      run_once: yes
      ignore_errors: yes
