---

- hosts: gluster
  remote_user: root
  tasks:
    - name: stop all volumes
      gluster_volume:
        name: "{{ item.name }}"
        state: "stopped"
      with_items: "{{ gluster_volume }}"
      run_once: yes
    
    - name: restart all nodes
      service:
        name: "glusterfs-server"
        state: "restarted"

    - name: start all volumes
      gluster_volume:
        name: "{{ item.name }}"
        state: "started"
      with_items: "{{ gluster_volume }}"
      run_once: yes
