---

- hosts: mariadb
  remote_user: root
  tasks:
    - name: bootstrap a new cluster with mysqld_safe
      shell: |
        mysqld_safe --wsrep-new-cluster > /dev/null 2>&1 &
        for i in $(seq 1 60); do
          sleep 1
          pgrep mysqld && break;
        done
      when: inventory_hostname == play_hosts[0]

    - name: add slave nodes to the cluster
      service:
        name: "mysql"
        state: "started"
      when: inventory_hostname != play_hosts[0]
    
    - name: stop master node
      shell: |
        killall -15 mysqld
        for i in $(seq 1 60); do
          sleep 1
          pgrep mysqld || break;
        done
      when: inventory_hostname == play_hosts[0]

    - name: readd master node to the cluster
      service:
        name: "mysql"
        state: "started"
      when: inventory_hostname == play_hosts[0]
    
