---

- hosts: mariadb
  remote_user: root
  tasks:
    - name: stop all slave nodes
      service:
        name: "mysql"
        state: "stopped"
      when: inventory_hostname != play_hosts[0]
    
    - name: stop master nodes
      service:
        name: "mysql"
        state: "stopped"
      when: inventory_hostname == play_hosts[0]

    - name: bootstrap a new cluster
      service:
        name: "mysql"
        state: "started"
        arguments: "--wsrep-new-cluster"
      when: inventory_hostname == play_hosts[0]

    - name: add slave nodes to the cluster
      service:
        name: "mysql"
        state: "started"
      when: inventory_hostname != play_hosts[0]
