---

- hosts: mysql
  remote_user: root
  roles:
    - hswong3i.mysql
    - role: hswong3i.ufw
      ufw_to_port:
        - { to_port: "{{ mysql_port }}", proto: "tcp", rule: "allow" }
  when: inventory_hostname not in groups['mariadb']
