---

- hosts: all
  remote_user: root
  serial: 1
  tasks:
    - name: apt-get dist-upgrade
      apt:
        cache_valid_time: "3600"
        update_cache: "yes"
        upgrade: "full"
      tags: hswong3i.apt

- hosts: all
  remote_user: root
  tasks:
    - name: setup ufw
      ufw:
        direction: "{{ item.direction | default(None) or omit }}"
        from_ip: "{{ item.from_ip | default(None) or omit }}"
        from_port: "{{ item.from_port | default(None) or omit }}"
        interface: "{{ item.interface | default(None) or omit }}"
        logging: "{{ item.logging | default(None) or omit }}"
        policy: "{{ item.policy | default(None) or omit }}"
        proto: "{{ item.proto | default(None) or omit }}"
        route: "{{ item.route | default(None) or omit }}"
        rule: "{{ item.rule | default(None) or omit }}"
        state: "{{ item.state | default(None) or omit }}"
        to_ip: "{{ item.to_ip | default(None) or omit }}"
        to_port: "{{ item.to_port | default(None) or omit }}"
      with_items:
        - { interface: "lo", direction: "in", rule: "allow" }
        - { from_ip: "224.0.0.0/4", rule: "allow" }
        - { from_ip: "10.0.0.0/8", rule: "allow" }
        - { from_ip: "172.16.0.0/12", rule: "allow" }
        - { from_ip: "192.168.0.0/16", rule: "allow" }
        - { to_port: "22", proto: "tcp", rule: "allow" }
        - { to_port: "1024:65535", proto: "tcp", rule: "allow" }
        - { direction: "incoming", policy: "deny" }
        - { direction: "outgoing", policy: "allow" }
        - { direction: "routed", policy: "allow" }
        - { logging: "on" }
        - { state: "enabled" }
      tags: hswong3i.ufw

- hosts: all
  remote_user: root
  roles:
    - hswong3i.apt
    - hswong3i.hostname
    - hswong3i.locales
    - hswong3i.tzdata
    - hswong3i.ntp
    - hswong3i.ufw
