---

- hosts: apache2
  remote_user: root
  roles:
    - hswong3i.apache2_vhosts

- hosts: mysql
  remote_user: root
  roles:
    - role: hswong3i.mysql_vhosts
      when: groups['mariadb'] is not defined or inventory_hostname not in groups['mariadb']

- hosts: mariadb
  remote_user: root
  roles:
    - hswong3i.mariadb_vhosts

- hosts: postgresql
  remote_user: root
  roles:
    - hswong3i.postgresql_vhosts

- hosts: php
  remote_user: root
  roles:
    - hswong3i.php_vhosts
